// Generated by scripts/build-video-manifest.ts — do not edit by hand.
export interface VideoManifestEntry {
  width: number;
  height: number;
  thumbhash: string | null;
}

export const videoManifest: Record<string, VideoManifestEntry> = {
  "/videos/flow/404.mp4": { width: 1920, height: 1144, thumbhash: "/QcCBIDxSWjPa3SIu0UwzUhQiQ==" },
  "/videos/flow/404.webm": { width: 1920, height: 1144, thumbhash: "/QcCBIDxSWjPa3SIu0UwzUhQig==" },
  "/videos/flow/company.mp4": { width: 1920, height: 1144, thumbhash: "r/cRFICWiYaMdpeKd4B3cAILxw==" },
  "/videos/flow/company.webm": { width: 1920, height: 1144, thumbhash: "r/cRFICWiYaMdpeKd4B3cAIL1w==" },
  "/videos/prodex/website-hero.mp4": { width: 1920, height: 1074, thumbhash: "L/gNDIC4qJd/dYVyiIdocYAEJw==" },
  "/videos/prodex/website-hero.webm": { width: 1920, height: 1074, thumbhash: "L/gNDIC4qJd/dYVyiIdocYAEJw==" },
  "/videos/prodex/website-tour.mp4": { width: 1920, height: 1074, thumbhash: "OQgGDIDjvxSHeIeKdXjQiAptmA==" },
  "/videos/prodex/website-tour.webm": { width: 1920, height: 1074, thumbhash: "OQgGDIDjvxSHeIeKdXjQiAptiA==" },
  "/videos/rogo/website-careers.mp4": { width: 1920, height: 1074, thumbhash: "/PcFBICId3iAd3hxh3F4gIAHCA==" },
  "/videos/rogo/website-careers.webm": { width: 1920, height: 1074, thumbhash: "/PcFBICId3iAd3hxh3F4gIAHCA==" },
  "/videos/rogo/website-hero.mp4": { width: 1920, height: 1074, thumbhash: "zMcFBIBnd4ePeHh6en2cb833tA==" },
  "/videos/rogo/website-hero.webm": { width: 1920, height: 1074, thumbhash: "zMcFBIBnd4ePeHh6en2cb833tA==" },
  "/videos/sona/hero-video.mp4": { width: 2520, height: 1500, thumbhash: "PggCBID3GOiEi3WMdH0Hh3BwCA==" },
  "/videos/sona/hero-video.webm": { width: 2520, height: 1500, thumbhash: "PggCBID3GOiEi3WMdH0Hh3BwCA==" },
  "/videos/sona/sona-use.mp4": { width: 1280, height: 720, thumbhash: "nygGFITFZ1X+onSFWJS/ifeFVw==" },
  "/videos/sona/sona-use.webm": { width: 1280, height: 720, thumbhash: "nygGFITFZ1X+onSFWZS/ifeFVw==" },
  "/videos/stock-footage.mp4": { width: 1920, height: 1080, thumbhash: "m/gJFIQeQ0Z/tWmJd3cpZWALhg==" },
  "/videos/superpower/health-categories.mp4": { width: 2520, height: 1500, thumbhash: "PfgBBICllq92iJiMlYnfiAEztA==" },
  "/videos/superpower/health-categories.webm": { width: 2520, height: 1500, thumbhash: "PfgBBICllq92iJiMlYnfiAFDtA==" },
  "/videos/superpower/protocol-reveal.mp4": { width: 2520, height: 1500, thumbhash: "AAgCBIDw8PDh4eFLS4cAAAAAAA==" },
  "/videos/superpower/protocol-reveal.webm": { width: 2520, height: 1500, thumbhash: "AAgCBIDw8PDh4eFLS4cAAAAAAA==" },
  "/videos/superpower/scroll-effect.mp4": { width: 2520, height: 1500, thumbhash: "PPgFBIDWWIhwfYWCfILi4JjvtQ==" },
  "/videos/superpower/scroll-effect.webm": { width: 2520, height: 1500, thumbhash: "PPgFBIDWWIhwfYWCfILj4JjvtQ==" },
  "/videos/writing/knight/gameplay.mp4": { width: 1920, height: 1074, thumbhash: "yucBDIAIp1azhpaGZZinkLP81g==" },
  "/videos/writing/knight/trailer.mp4": { width: 1920, height: 1080, thumbhash: "AAgCBIAAAAAAAAAAAAAAAAAAAA==" },
  "/videos/writing/loading-states/clip-1080.mp4": { width: 1080, height: 1920, thumbhash: "necNRAao+IWXd5doeZiFcGUIRA==" },
  "/videos/writing/loading-states/clip-240.mp4": { width: 240, height: 426, thumbhash: "necNRAao+IWXd5doeZiFcGUIRQ==" },
  "/videos/writing/loading-states/clip-480.mp4": { width: 480, height: 854, thumbhash: "necNRAao+IWXd5doeZiFcGUIRQ==" },
  "/videos/writing/loading-states/clip-720.mp4": { width: 720, height: 1280, thumbhash: "necNRAao+IWXd5doeZiFcGUIRQ==" },
};
